### ISSUE TITLE
CORS 이슈

### ISSUE THREAD

**Issue by hhhminme** [kpuce2022CD/hummingbird#25]
### Describe the bug
<img width="961" alt="image" src="https://user-images.githubusercontent.com/54930877/159009696-4274179d-2847-4526-9b68-d1c57b38d346.png">

### To Reproduce
API 통신 시 CORS 에러가 발생하였습니다. 
이를 해결하기 위해 클라이언트에선 프록시 설정, "Access-Control-Allow-Origin" 추가, 크롬 CROS 설정 끄기를 해보았습니다.
임시로 middleware library를 설치를 하게되면 dev 환경에서 작동이 될 수 있으나 prod 에서 api가 작동하지 않습니다. 

**config 랑 anotation 추가 한번만 확인 부탁드립니다.!** 

### Additional context
추가적 사항을 적어주세요.

**Comment by kim1387** [comment]
![image](https://user-images.githubusercontent.com/58874807/159450184-0ed7cda3-ad14-4b8d-9fc6-3ba7677beb53.png)
이런 식으로 되면 cors 해결된거지??
저번에 test 했을때 400에러 났던거 같아서 이러면 된거 같기도?

**Comment by hhhminme** [comment]
@kim1387 엉 cors는 해결된거 같아 프론트에서 아마 id에 number가 아니라 string이 들어가서 그런걸거야 고마워~~ 코드 develop-2에 pr 날려줘라
